apiVersion: v1
kind: Secret
metadata:
  name: post-service-secret
  namespace: default
  labels:
    app: post-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://<user>:<password>@post-postgres-service:5432/<db>"
  SECRET_KEY: "<same-secret-key-as-auth-service>"
