# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\rcampus_assist\"h\n\x17SendNotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x11\n\tdata_json\x18\x05 \x01(\t\"U\n\x18SendNotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fnotification_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\\\n\x1bSendBulkNotificationRequest\x12=\n\rnotifications\x18\x01 \x03(\x0b\x32&.campus_assist.SendNotificationRequest\"O\n\x1cSendBulkNotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\xeb\x01\n\x13NotificationService\x12\x63\n\x10SendNotification\x12&.campus_assist.SendNotificationRequest\x1a\'.campus_assist.SendNotificationResponse\x12o\n\x14SendBulkNotification\x12*.campus_assist.SendBulkNotificationRequest\x1a+.campus_assist.SendBulkNotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_start=37
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_end=141
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_start=143
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_end=228
  _globals['_SENDBULKNOTIFICATIONREQUEST']._serialized_start=230
  _globals['_SENDBULKNOTIFICATIONREQUEST']._serialized_end=322
  _globals['_SENDBULKNOTIFICATIONRESPONSE']._serialized_start=324
  _globals['_SENDBULKNOTIFICATIONRESPONSE']._serialized_end=403
  _globals['_NOTIFICATIONSERVICE']._serialized_start=406
  _globals['_NOTIFICATIONSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
