# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from notification.grpc import notification_pb2 as notification__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub(object):
    """NotificationService is served by notification_service on gRPC port 50056.

    Other microservices (post_service, comment_service, community_service …) call
    SendNotification whenever they want to notify a user of an event.
    SendBulkNotification is a batch variant for community-wide broadcasts.

    The servicer:
    1. Persists the notification to Postgres (ACID, with session.commit).
    2. Attempts a best-effort WebSocket push to the recipient if they are
    currently connected.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNotification = channel.unary_unary(
                '/campus_assist.NotificationService/SendNotification',
                request_serializer=notification__pb2.SendNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.SendNotificationResponse.FromString,
                _registered_method=True)
        self.SendBulkNotification = channel.unary_unary(
                '/campus_assist.NotificationService/SendBulkNotification',
                request_serializer=notification__pb2.SendBulkNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.SendBulkNotificationResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """NotificationService is served by notification_service on gRPC port 50056.

    Other microservices (post_service, comment_service, community_service …) call
    SendNotification whenever they want to notify a user of an event.
    SendBulkNotification is a batch variant for community-wide broadcasts.

    The servicer:
    1. Persists the notification to Postgres (ACID, with session.commit).
    2. Attempts a best-effort WebSocket push to the recipient if they are
    currently connected.
    """

    def SendNotification(self, request, context):
        """Persist and (optionally) push a single notification to one user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBulkNotification(self, request, context):
        """Persist and push notifications for multiple users in a single call.
        Useful for community broadcasts (e.g. new post in a large community).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=notification__pb2.SendNotificationRequest.FromString,
                    response_serializer=notification__pb2.SendNotificationResponse.SerializeToString,
            ),
            'SendBulkNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBulkNotification,
                    request_deserializer=notification__pb2.SendBulkNotificationRequest.FromString,
                    response_serializer=notification__pb2.SendBulkNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'campus_assist.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('campus_assist.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """NotificationService is served by notification_service on gRPC port 50056.

    Other microservices (post_service, comment_service, community_service …) call
    SendNotification whenever they want to notify a user of an event.
    SendBulkNotification is a batch variant for community-wide broadcasts.

    The servicer:
    1. Persists the notification to Postgres (ACID, with session.commit).
    2. Attempts a best-effort WebSocket push to the recipient if they are
    currently connected.
    """

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.NotificationService/SendNotification',
            notification__pb2.SendNotificationRequest.SerializeToString,
            notification__pb2.SendNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBulkNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.NotificationService/SendBulkNotification',
            notification__pb2.SendBulkNotificationRequest.SerializeToString,
            notification__pb2.SendBulkNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
