apiVersion: v1
kind: ConfigMap
metadata:
  name: attachment-service-config
  namespace: default
  labels:
    app: attachment-service
data:
  APP_NAME: "Attachment Service"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8004"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET: "campus-assist"
  MINIO_SECURE: "false"
  GRPC_PORT: "50054"
  AUTH_GRPC_TARGET: "auth-service:50051"
