apiVersion: v1
kind: Secret
metadata:
  name: attachment-service-secret
  namespace: default
  labels:
    app: attachment-service
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_ME"
  SECRET_KEY: "REPLACE_ME"
  MINIO_ACCESS_KEY: "REPLACE_ME"
  MINIO_SECRET_KEY: "REPLACE_ME"
