apiVersion: v1
kind: Secret
metadata:
  name: comment-service-secret
  namespace: default
  labels:
    app: comment-service
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_ME"
  SECRET_KEY: "REPLACE_ME"
