apiVersion: v1
kind: Secret
metadata:
  name: attachment-postgres-secret
  namespace: default
  labels:
    app: attachment-postgres
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "REPLACE_ME"
