apiVersion: v1
kind: Service
metadata:
  name: attachment-postgres-service
  namespace: default
  labels:
    app: attachment-postgres
spec:
  type: ClusterIP
  selector:
    app: attachment-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
