apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: default
  labels:
    app: user-service
data:
  APP_NAME: "User Service"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  ALGORITHM: "HS256"
  AUTH_GRPC_TARGET: "auth-service:50051"
  POST_SERVICE_URL: "http://post-service"
  COMMENT_SERVICE_URL: "http://comment-service"
  COMMUNITY_SERVICE_URL: "http://community-service"
  STATS_CACHE_TTL_SECONDS: "300"
