apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: default
  labels:
    app: user-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://<user>:<password>@user-postgres-service:5432/<db>"
  SECRET_KEY: "<same-secret-key-as-auth-service>"
