# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attachment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'attachment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ttachment.proto\x12\nattachment\"E\n\x1aValidateAttachmentsRequest\x12\x16\n\x0e\x61ttachment_ids\x18\x01 \x03(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"A\n\x1bValidateAttachmentsResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x13\n\x0binvalid_ids\x18\x02 \x03(\t\"C\n\x18\x44\x65leteAttachmentsRequest\x12\x16\n\x0e\x61ttachment_ids\x18\x01 \x03(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"Q\n\x19\x44\x65leteAttachmentsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nfailed_ids\x18\x03 \x03(\t2\xdd\x01\n\x11\x41ttachmentService\x12\x66\n\x13ValidateAttachments\x12&.attachment.ValidateAttachmentsRequest\x1a\'.attachment.ValidateAttachmentsResponse\x12`\n\x11\x44\x65leteAttachments\x12$.attachment.DeleteAttachmentsRequest\x1a%.attachment.DeleteAttachmentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attachment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEATTACHMENTSREQUEST']._serialized_start=32
  _globals['_VALIDATEATTACHMENTSREQUEST']._serialized_end=101
  _globals['_VALIDATEATTACHMENTSRESPONSE']._serialized_start=103
  _globals['_VALIDATEATTACHMENTSRESPONSE']._serialized_end=168
  _globals['_DELETEATTACHMENTSREQUEST']._serialized_start=170
  _globals['_DELETEATTACHMENTSREQUEST']._serialized_end=237
  _globals['_DELETEATTACHMENTSRESPONSE']._serialized_start=239
  _globals['_DELETEATTACHMENTSRESPONSE']._serialized_end=320
  _globals['_ATTACHMENTSERVICE']._serialized_start=323
  _globals['_ATTACHMENTSERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
