apiVersion: v1
kind: Secret
metadata:
  name: search-service-secret
  namespace: default
  labels:
    app: search-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://<user>:<password>@search-postgres-service:5432/<db>"
  SECRET_KEY: "<same-secret-key-as-auth-service>"
