apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 80
      targetPort: 8006
      protocol: TCP
    - name: grpc
      port: 50056
      targetPort: 50056
      protocol: TCP
