# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import college_pb2 as college__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in college_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollegeServiceStub(object):
    """CollegeService is served by college_service on its gRPC port (default 50055).
    Used by community_service to manage college memberships and by other services to look up colleges.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCollege = channel.unary_unary(
                '/campus_assist.CollegeService/GetCollege',
                request_serializer=college__pb2.GetCollegeRequest.SerializeToString,
                response_deserializer=college__pb2.GetCollegeResponse.FromString,
                _registered_method=True)
        self.RecordMembership = channel.unary_unary(
                '/campus_assist.CollegeService/RecordMembership',
                request_serializer=college__pb2.RecordMembershipRequest.SerializeToString,
                response_deserializer=college__pb2.RecordMembershipResponse.FromString,
                _registered_method=True)
        self.RemoveMembership = channel.unary_unary(
                '/campus_assist.CollegeService/RemoveMembership',
                request_serializer=college__pb2.RemoveMembershipRequest.SerializeToString,
                response_deserializer=college__pb2.RemoveMembershipResponse.FromString,
                _registered_method=True)


class CollegeServiceServicer(object):
    """CollegeService is served by college_service on its gRPC port (default 50055).
    Used by community_service to manage college memberships and by other services to look up colleges.
    """

    def GetCollege(self, request, context):
        """Retrieve a college record by UUID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMembership(self, request, context):
        """Record that a user is now a member of the college (via one of its communities).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMembership(self, request, context):
        """Remove a user's membership from the college.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollegeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCollege': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollege,
                    request_deserializer=college__pb2.GetCollegeRequest.FromString,
                    response_serializer=college__pb2.GetCollegeResponse.SerializeToString,
            ),
            'RecordMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMembership,
                    request_deserializer=college__pb2.RecordMembershipRequest.FromString,
                    response_serializer=college__pb2.RecordMembershipResponse.SerializeToString,
            ),
            'RemoveMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMembership,
                    request_deserializer=college__pb2.RemoveMembershipRequest.FromString,
                    response_serializer=college__pb2.RemoveMembershipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'campus_assist.CollegeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('campus_assist.CollegeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollegeService(object):
    """CollegeService is served by college_service on its gRPC port (default 50055).
    Used by community_service to manage college memberships and by other services to look up colleges.
    """

    @staticmethod
    def GetCollege(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.CollegeService/GetCollege',
            college__pb2.GetCollegeRequest.SerializeToString,
            college__pb2.GetCollegeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.CollegeService/RecordMembership',
            college__pb2.RecordMembershipRequest.SerializeToString,
            college__pb2.RecordMembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.CollegeService/RemoveMembership',
            college__pb2.RemoveMembershipRequest.SerializeToString,
            college__pb2.RemoveMembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
