# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: community.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'community.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ommunity.proto\x12\rcampus_assist\"?\n\x16\x43heckMembershipRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"T\n\x17\x43heckMembershipResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x11\n\tis_member\x18\x02 \x01(\x08\x12\x16\n\x0e\x63ommunity_name\x18\x03 \x01(\t2t\n\x10\x43ommunityService\x12`\n\x0f\x43heckMembership\x12%.campus_assist.CheckMembershipRequest\x1a&.campus_assist.CheckMembershipResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKMEMBERSHIPREQUEST']._serialized_start=34
  _globals['_CHECKMEMBERSHIPREQUEST']._serialized_end=97
  _globals['_CHECKMEMBERSHIPRESPONSE']._serialized_start=99
  _globals['_CHECKMEMBERSHIPRESPONSE']._serialized_end=183
  _globals['_COMMUNITYSERVICE']._serialized_start=185
  _globals['_COMMUNITYSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
