apiVersion: v1
kind: Secret
metadata:
  name: college-service-secret
  namespace: default
  labels:
    app: college-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://<user>:<password>@college-postgres-service:5432/<db>"
  SECRET_KEY: "<same-secret-key-as-auth-service>"
