# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: college.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'college.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcollege.proto\x12\rcampus_assist\"\'\n\x11GetCollegeRequest\x12\x12\n\ncollege_id\x18\x01 \x01(\t\"\x98\x01\n\x12GetCollegeResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rcontact_email\x18\x04 \x01(\t\x12\x18\n\x10physical_address\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x64min_users\x18\x06 \x03(\t\x12\x13\n\x0b\x63ommunities\x18\x07 \x03(\t\">\n\x17RecordMembershipRequest\x12\x12\n\ncollege_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"<\n\x18RecordMembershipResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x17RemoveMembershipRequest\x12\x12\n\ncollege_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"<\n\x18RemoveMembershipResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xad\x02\n\x0e\x43ollegeService\x12Q\n\nGetCollege\x12 .campus_assist.GetCollegeRequest\x1a!.campus_assist.GetCollegeResponse\x12\x63\n\x10RecordMembership\x12&.campus_assist.RecordMembershipRequest\x1a\'.campus_assist.RecordMembershipResponse\x12\x63\n\x10RemoveMembership\x12&.campus_assist.RemoveMembershipRequest\x1a\'.campus_assist.RemoveMembershipResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'college_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCOLLEGEREQUEST']._serialized_start=32
  _globals['_GETCOLLEGEREQUEST']._serialized_end=71
  _globals['_GETCOLLEGERESPONSE']._serialized_start=74
  _globals['_GETCOLLEGERESPONSE']._serialized_end=226
  _globals['_RECORDMEMBERSHIPREQUEST']._serialized_start=228
  _globals['_RECORDMEMBERSHIPREQUEST']._serialized_end=290
  _globals['_RECORDMEMBERSHIPRESPONSE']._serialized_start=292
  _globals['_RECORDMEMBERSHIPRESPONSE']._serialized_end=352
  _globals['_REMOVEMEMBERSHIPREQUEST']._serialized_start=354
  _globals['_REMOVEMEMBERSHIPREQUEST']._serialized_end=416
  _globals['_REMOVEMEMBERSHIPRESPONSE']._serialized_start=418
  _globals['_REMOVEMEMBERSHIPRESPONSE']._serialized_end=478
  _globals['_COLLEGESERVICE']._serialized_start=481
  _globals['_COLLEGESERVICE']._serialized_end=782
# @@protoc_insertion_point(module_scope)
