apiVersion: v1
kind: ConfigMap
metadata:
  name: community-service-config
  namespace: default
  labels:
    app: community-service
data:
  APP_NAME: "Community Service"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  GRPC_PORT: "50052"
  COLLEGE_GRPC_TARGET: "college-service:50055"
  AUTH_GRPC_TARGET: "auth-service:50051"
