apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: college-postgres-pvc
  namespace: default
  labels:
    app: college-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
