apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-config
  namespace: default
  labels:
    app: admin-service
data:
  APP_NAME: "Admin Service"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8005"
  AUTH_GRPC_TARGET: "auth-service:50051"
  AUTH_SERVICE_URL: "http://auth-service:80"
  COMMUNITY_SERVICE_URL: "http://community-service:80"
  POST_SERVICE_URL: "http://post-service:80"
  COMMENT_SERVICE_URL: "http://comment-service:80"
  ATTACHMENT_SERVICE_URL: "http://attachment-service:80"
  COLLEGE_SERVICE_URL: "http://college-service:80"
