apiVersion: v1
kind: Secret
metadata:
  name: community-service-secret
  namespace: default
  labels:
    app: community-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://<user>:<password>@community-postgres-service:5432/<db>"
