apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-postgres
spec:
  template:
    spec:
      containers:
        - name: post-postgres
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
