# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import post_pb2 as post__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in post_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostServiceStub(object):
    """PostService is served by post_service on its gRPC port (default 50053).
    It exposes AddComment / RemoveComment RPCs used by comment_service to keep
    the post's comments UUID array in sync — replacing the former httpx calls to
    POST/DELETE /api/posts/{post_id}/comments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddComment = channel.unary_unary(
                '/campus_assist.PostService/AddComment',
                request_serializer=post__pb2.PostCommentRequest.SerializeToString,
                response_deserializer=post__pb2.PostCommentResponse.FromString,
                _registered_method=True)
        self.RemoveComment = channel.unary_unary(
                '/campus_assist.PostService/RemoveComment',
                request_serializer=post__pb2.PostCommentRequest.SerializeToString,
                response_deserializer=post__pb2.PostCommentResponse.FromString,
                _registered_method=True)


class PostServiceServicer(object):
    """PostService is served by post_service on its gRPC port (default 50053).
    It exposes AddComment / RemoveComment RPCs used by comment_service to keep
    the post's comments UUID array in sync — replacing the former httpx calls to
    POST/DELETE /api/posts/{post_id}/comments.
    """

    def AddComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddComment': grpc.unary_unary_rpc_method_handler(
                    servicer.AddComment,
                    request_deserializer=post__pb2.PostCommentRequest.FromString,
                    response_serializer=post__pb2.PostCommentResponse.SerializeToString,
            ),
            'RemoveComment': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveComment,
                    request_deserializer=post__pb2.PostCommentRequest.FromString,
                    response_serializer=post__pb2.PostCommentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'campus_assist.PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('campus_assist.PostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """PostService is served by post_service on its gRPC port (default 50053).
    It exposes AddComment / RemoveComment RPCs used by comment_service to keep
    the post's comments UUID array in sync — replacing the former httpx calls to
    POST/DELETE /api/posts/{post_id}/comments.
    """

    @staticmethod
    def AddComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.PostService/AddComment',
            post__pb2.PostCommentRequest.SerializeToString,
            post__pb2.PostCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus_assist.PostService/RemoveComment',
            post__pb2.PostCommentRequest.SerializeToString,
            post__pb2.PostCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
