# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\rcampus_assist\"9\n\x12PostCommentRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x12\n\ncomment_id\x18\x02 \x01(\t\"7\n\x13PostCommentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x01\n\x0bPostService\x12S\n\nAddComment\x12!.campus_assist.PostCommentRequest\x1a\".campus_assist.PostCommentResponse\x12V\n\rRemoveComment\x12!.campus_assist.PostCommentRequest\x1a\".campus_assist.PostCommentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTCOMMENTREQUEST']._serialized_start=29
  _globals['_POSTCOMMENTREQUEST']._serialized_end=86
  _globals['_POSTCOMMENTRESPONSE']._serialized_start=88
  _globals['_POSTCOMMENTRESPONSE']._serialized_end=143
  _globals['_POSTSERVICE']._serialized_start=146
  _globals['_POSTSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
