apiVersion: v1
kind: Secret
metadata:
  name: comment-postgres-secret
  namespace: default
  labels:
    app: comment-postgres
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "REPLACE_ME"
