apiVersion: v1
kind: Secret
metadata:
  name: search-postgres-secret
  namespace: default
  labels:
    app: search-postgres
type: Opaque
stringData:
  POSTGRES_USER: "<user>"
  POSTGRES_PASSWORD: "<password>"
  POSTGRES_DB: "<db>"
